Complete Your First Project in R
Classification Analysis

```{r}

#run first
library(openxlsx)
sales <- read.xlsx("Red30 Tech Sales.xlsx",1,detectDates = TRUE)

sales$OrderMonth <- format(sales$OrderDate,"%B")
sales$OrderYear <- format(sales$OrderDate,"%Y")
sales$Payment.Status <- factor(sales$Payment.Status)
summary(sales)
```

```{r}
#run first
sales_subset <- subset(sales, select = c(Employee.Job.Title , Sales.Region , OrderMonth
                     ,OrderYear , OrderType , CustomerType , ProdCategory
                     , Quantity , Price , Discount , Order.Total , Payment.Plan, Payment.Status))

set.seed(42)
bound <- floor((nrow(sales_subset)/4)*3)         #define % of training and test set

df <- sales_subset[sample(nrow(sales_subset)), ]           #sample rows 
train <- df[1:bound, ]              #get training set
test <- df[(bound+1):nrow(df), ]    #get test set
summary(train)
summary(test)
```

```{r}
#install packages if needed
install.packages("rpart")
install.packages("tidymodels")
install.packages("rpart.plot")
install.packages("Boruta")
install.packages("randomForest")
```


```{r}
#load packages
library(tidymodels)
library(rpart)
library(rpart.plot)
library(yardstick)
library(Boruta)
library(randomForest)
```

```{r}
# Variable Selection

set.seed(42) # For reproducibility

# Run Boruta on the training dataset
boruta_results <- Boruta(Payment.Status ~ ., data = train, doTrace = 2)

# Print the results
print(boruta_results)

# Plot Boruta results
plot(boruta_results, las = 2, main = "Boruta Feature Importance")


```

```{r}
#create decision tree model
tree <- decision_tree() %>% 
  set_engine("rpart") %>%
  set_mode("classification")
```

```{r}
#create recipe
df_recipe <- recipe(Payment.Status~ .,data=df) %>%
  step_normalize(all_numeric())
```

```{r}
#create decision tree workflow
tree_wf <- workflow() %>%
  add_recipe(df_recipe) %>%
  add_model(tree) %>%
  fit(train)
```

```{r}
#get summary of tree_wf
summary(tree_wf)
```

```{r}
#predict on model
pred_results <- data.frame(predict(tree_wf, test))
colnames(pred_results) <- c("test_pred_tree")
test <- cbind(test, pred_results)
test

```

```{r}
# Evaluation Metrics

# Confusion matrix
conf_mat(test, truth = Payment.Status, estimate = test_pred_tree)

# Accuracy
accuracy(test, truth = Payment.Status, estimate = test_pred_tree)
```
```{r, fig.width = 15, fig.height=7}
#plot decision tree
fit <- rpart(Payment.Status~ ., data=train, method = "class")
rpart.plot(fit, type = 2, extra = 104, fallen.leaves = TRUE, tweak = 1.2)

```




